apiVersion: networking.istio.io/v1beta1
kind: Gateway 
metadata:
  name: spring-boot-app-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: second-app
        protocol: HTTP 
      hosts:
        - "*"